Detected,Issue,Related to Tensor,Version,Buggy API,Category,Impact,Log Rule,Log Message,Category,Trigger Mechanism,Description,Need More Inspection(0/1),Reason not agree,,Time,Related,CUDA
,https://github.com/tensorflow/tensorflow/issues/62174,yes,2.14.0,tf.map_fn,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,tf.map_fn and TensorArray do not seem to support backpropagation,,,,2023-10-19T12:34:32Z,1,N.A
ACETest,https://github.com/tensorflow/tensorflow/issues/62146,yes,2.14.0,tf.raw_ops.BiasAdd,Vulnerability,Check failed,Aborted (core dumped),"2023-10-18 13:29:08.644285: F tensorflow/core/framework/tensor_shape.cc:357] Check failed: d < dims() (2 vs. 2)
Aborted (core dumped)",API Input Context,Generating Tensors with Incompatible Shapes,Improper input validation,,,,2023-10-18T05:32:47Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/62142,yes,2.14.0,tf.raw_ops.Conv2DBackpropFilter,Vulnerability,Check failed,Aborted (core dumped),"2023-10-18 01:54:46.384973: F ./tensorflow/core/util/tensor_format.h:428] Check failed: index >= 0 && index < num_total_dims Invalid index from the dimension: 3, 0,
Aborted (core dumped)",API Input Context,Generating Tensors with Incompatible Shapes,Improper input validation,,,,2023-10-17T17:58:27Z,1,cu118
ACETest,https://github.com/tensorflow/tensorflow/issues/62140,yes,2.14.0,tf.raw_ops.BiasAddGrad,Vulnerability,Check failed,Aborted (core dumped),"2023-10-17 22:20:56.471424: F tensorflow/core/framework/tensor_shape.cc:357] Check failed: d < dims() (2 vs. 2)
Aborted (core dumped)",API Input Context,Generating Tensors with Incompatible Shapes,Improper input validation,,,,2023-10-17T14:32:50Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/62114,yes,2.14.0,tf.truncatediv,Logical,Others,Internal error,Internal error,API Input Context,Zero Integer Argument,Internal Error for truncatediv when denominator is an integer zero,,,,2023-10-15T05:48:56Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/62088,yes,2.14.0,tf.gather,Logical,InvalidArgumentError,is not compatible with result shape,"tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__GatherV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Shape used to set computation result layout (s32[3,2]{1,0}) is not compatible with result shape (s32[2,2])
         [[{{node cluster_1_1/xla_compile}}]] [Op:GatherV2] name:",API Input Context,Generating Tensors with Incompatible Shapes,"But looks like the doc does not tell us what to do when the batch_dim dimensions of params and indices disagree. Should the formula be updated to something like: def batched_result_shape(p_shape, i_shape, axis=0, batch_dims=0):
return i_shape[:batch_dims] + p_shape[batch_dims:axis] + i_shape[batch_dims:] + p_shape[axis+1:] or, should we just add a validation check to count the mismatch of batch_dim dimensions of params and indices?",,,,2023-10-11T12:07:56Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/62070,yes,2.14.0,tf.truncatemod,Logical,NotFoundError,Could not find device for node,NotFoundError: Could not find device for node: {{node TruncateMod}} = TruncateMod[T=DT_BFLOAT16],API Input Context,Supporting Specific Data Types,supports the half and bfloat16 data type but in practical it does not.,,,,2023-10-09T08:36:40Z,1,N.A
ACETest,https://github.com/tensorflow/tensorflow/issues/62055,yes,2.14.0,tf.raw_ops.QuantizeAndDequantizeV4,Vulnerability,Check failed,Aborted (core dumped),"2023-10-05 23:52:38.268849: F tensorflow/core/framework/tensor.cc:852] Check failed: 1 == NumElements() (1 vs. 0)Must have a one element tensor
Aborted (core dumped)",API Input Context,Empty Input Tensor,core dumped error with specific input parameters,,,,2023-10-05T15:56:08Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/62006,no,2.13.0,tf.train.Checkpoint.restore,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-09-28T15:49:30Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/61968,yes,2.14.0,tf.transpose,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-09-25T00:12:15Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61965,yes,2.14.0,tf.math.floordiv,Vulnerability,InvalidArgumentError,Integer division by zero,InvalidArgumentError: Exception encountered when calling layer 'model_21' (type Model). {{function_node __wrapped__FloorDiv_device_/job:localhost/replica:0/task:0/device:CPU:0}} Integer division by zero [Op:FloorDiv] name:,API Input Context,Empty Input Tensor,,,,,2023-09-23T19:51:17Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61955,yes,2.13.0,tf.linalg.svd,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-09-23T08:44:22Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61938,yes,2.14.0,tf.keras.layers.Embedding,Logical,InvalidArgumentError,Exception encountered when calling layer,"InvalidArgumentError: Exception encountered when calling layer 'embedding_4' (type Embedding). {{function_node __wrapped__ResourceGather_device_/job:localhost/replica:0/task:0/device:CPU:0}} indices[0] = 64 is not in [0, 64) [Op:ResourceGather] name:",API Input Context,Large Input Tensor,,,,,2023-09-21T12:57:04Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61925,yes,2.13.0,tf.keras.layers.Concatenate,Logical,ValueError,layer requires inputs with matching shapes,raise ValueError(err_msg) ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received:,API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-09-20T07:51:32Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61916,yes,2.13.0,tf.linalg.cholesky,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Supporting Specific Data Types,,,,,2023-09-19T13:54:42Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61911,no,2.13.0,tf.device,Logical,Others,cudaError_t.cudaSuccess,"(<cudaError_t.cudaSuccess: 0>, 0)
(<cudaError_t.cudaSuccess: 0>, 7)
(<cudaError_t.cudaSuccess: 0>, 7)
(<cudaError_t.cudaSuccess: 0>, 0)",API Input Context,Modeling Specific Devices,,1,"trigger: This happens when: 1. tensorflow is initializing GPU context on this line (tf.device), 2. there is no materialization of tensors on GPU",,2023-09-19T10:21:44Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61907,yes,2.13.0,tf.linalg.cholesky,Logical,NotFoundError,Could not find device for node,"NotFoundError: Could not find device for node: {{node Cholesky}} = Cholesky[T=DT_HALF]
All kernels registered for op Cholesky:",API Input Context,Supporting Specific Data Types,"unsupported data type
expected to accept tensor in half precision but it fails",,,,2023-09-19T05:37:10Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61875,yes,2.12.0,tf.cast,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Large Input Tensor,casting round issue,,,,2023-09-15T12:50:23Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61866,no,2.12.0,tf.keras.layers.StringLookup,Performance bug,Performance bug,Memory Leak,Memory Leak,Test Case Context,Oracle for Performance Bug Detection,,,,,2023-09-14T17:44:28Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61861,yes,2.13.0,tf.nn.elu,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Others,Others,,,,,2023-09-14T13:33:11Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61856,yes,2.13.0,tf.reshape,Logical,ValueError,Shape must be rank 1 but is rank,"ValueError: Shape must be rank 1 but is rank 0 for '{{node Reshape_1}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](Reshape, Reshape_1/shape)' with input shapes: [2,2], [].",API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-09-13T21:09:29Z,1,N.A
FuzzGPT,https://github.com/tensorflow/tensorflow/issues/61827,yes,2.13.0,tf.linalg.eigvals,Logical,Others,referenced before assignment,UnboundLocalError: local variable 'out_dtype' referenced before assignment,API Input Context,Supporting Specific Data Types,,,,,2023-09-10T15:58:12Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61826,yes,2.13.0,tf.linalg.eigvals,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Usage Context,Modeling Specific Inputs,,,,,2023-09-10T15:54:18Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61820,yes,2.14.0,tf.compat.v1.boolean_mask,Logical,Others,Failed,"[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
Failed!",API Input Context,Supporting Specific Data Types,"I think it's worth updating the documentation to state that the mask will be cast to boolean if it is not a boolean Tensor, or warning users that the mask dtype should be boolean.",,,,2023-09-09T09:40:31Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61815,yes,2.13.0,tf.keras.layers.DepthwiseConv2D,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-09-08T14:16:17Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61800,yes,2.14.0,tf.nn.sigmoid,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Supporting Specific Data Types,,,,,2023-09-06T11:59:27Z,1,N.A
FreeFuzz,https://github.com/tensorflow/tensorflow/issues/61780,yes,2.14.0,tf.gather,Vulnerability,Check failed,Aborted (core dumped),"v2.14.0-rc0-34-gdd01672d9a9 2.14.0-rc1
2023-09-03 13:08:24.487989: F ./tensorflow/core/util/gpu_launch_config.h:160] Check failed: work_element_count >= 0 (0 vs. -549025096)
Aborted (core dumped)",API Input Context,Large Input Tensor,,,,,2023-09-03T14:31:11Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61778,yes,2.14.0,tf.keras.layers.MaxPooling1D,Vulnerability,Check failed,Aborted (core dumped),"2023-09-03 11:34:09.267078: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8600
2023-09-03 11:34:09.267132: F tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:1019] Check failed: cudnnSetPoolingNdDescriptor( handle_.get(), (pooling_descriptor.mode() == dnn::PoolingMode::kMaximum ? cudnn_max_pooling_mode : CUDNN_POOLING_AVERAGE_COUNT_EXCLUDE_PADDING), propagate_nans ? CUDNN_PROPAGATE_NAN : CUDNN_NOT_PROPAGATE_NAN, nd, shape.data(), padding.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)
Aborted (core dumped)",API Input Context,Large Integer Argument,,,,,2023-09-03T14:26:52Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61761,yes,2.14.0,tf.raw_ops.Enter,Logical,NotFoundError,Could not find device for node,"tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node Enter}} = Enter[T=DT_QINT8, frame_name=""test"", is_constant=true, parallel_iterations=10]
All kernels registered for op Enter:",API Input Context,Supporting Specific Data Types,,,,,2023-08-31T08:49:00Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61736,yes,2.13.0,tf.data.Dataset.save,Performance bug,Performance bug,deadlocks,deadlocks,API Usage Context,Modeling Specific Inputs,,1,I think the trigger is wrong. Check again.,,2023-08-28T22:43:16Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61712,yes,2.13.0,tf.function,Logical,ValueError,Structure of Python function inputs does not match input_signature,ValueError: Structure of Python function inputs does not match input_signature:,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-08-27T12:47:18Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61701,yes,2.13.0,tf.math.top_k,Logical,InvalidArgumentError,was expected to be a int64 tensor,tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int64 tensor but is a int32 tensor [Op:AddV2] name:,API Input Context,Supporting Specific Data Types,,1,Maybe Specific Input argument?,,2023-08-25T18:38:43Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61675,yes,2.13.0,tf.linalg.pinv,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Usage Context,Modeling Specific Inputs,,1,I think it's something diffrerent,,2023-08-23T13:32:23Z,1,N.A
FreeFuzz,https://github.com/tensorflow/tensorflow/issues/61780,yes,2.14.0,tf.compat.v1.gather,Vulnerability,Check failed,Aborted (core dumped),"2023-09-03 13:08:24.487989: F ./tensorflow/core/util/gpu_launch_config.h:160] Check failed: work_element_count >= 0 (0 vs. -549025096)
Aborted (core dumped)",API Input Context,Large Input Tensor,,,,,2023-09-03T14:31:11Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61643,yes,2.13.0,tf.keras.layers.RepeatVector,Vulnerability,Check failed,Aborted,"2023-08-18 22:31:59.138979: F tensorflow/tsl/framework/bfc_allocator.cc:797] Check failed: c->in_use() && (c->bin_num == kInvalidBinNum) 
Aborted",API Input Context,Large Integer Argument,,,,,2023-08-19T02:33:17Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/61642,yes,2.13.0,tf.compat.v1.layers.MaxPooling1D,Vulnerability,Check failed,Aborted,"2023-08-18 22:04:08.473555: F tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:983] Check failed: cudnnSetPoolingNdDescriptor( handle_.get(), (pooling_descriptor.mode() == dnn::PoolingMode::kMaximum ? cudnn_max_pooling_mode : CUDNN_POOLING_AVERAGE_COUNT_EXCLUDE_PADDING), propagate_nans ? CUDNN_PROPAGATE_NAN : CUDNN_NOT_PROPAGATE_NAN, nd, shape.data(), padding.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)
Aborted",API Input Context,Large List Element,,,,,2023-08-19T02:28:18Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/61639,yes,2.14.0,tf.math.softmax,Logical,InvalidArgumentError,invalid configuration argument,"Non-OK-status: GpuLaunchKernel( GenerateNormalizedProb<T, acc_type, kUnroll>, numBlocks, numThreadsPerBlock, 0, cu_stream, reinterpret_cast<const T*>(logits_in_.flat().data()), reinterpret_cast<const acc_type*>( sum_probs.flat<acc_type>().data()), reinterpret_cast<const T*>(max_logits.flat().data()), const_cast<T*>(softmax_out->flat().data()), rows, cols, log_) status: INTERNAL: invalid configuration argument",API Input Context,Large List Element,,,,,2023-08-18T13:55:11Z,1,cu118
DocTer,https://github.com/tensorflow/tensorflow/issues/61605,yes,2.13.0,tf.keras.layers.MaxPool2D,Vulnerability,Check failed,Allocation of,"{""pid"":7,""type"":""jupyter"",""level"":40,""msg"":""2023-08-17 14:26:40.077428: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 6093750902 exceeds 10% of free system memory."",""time"":""2023-08-17T14:26:40.077Z"",""v"":0}
{""pid"":7,""type"":""jupyter"",""level"":40,""msg"":""2023-08-17 14:26:42.860963: F tensorflow/core/framework/tensor_shape.cc:587] Check failed: size >= 0 (0 vs. -1248091845)"",""time"":""2023-08-17T14:26:42.861Z"",""v"":0}",API Input Context,Large List Element,,,,,2023-08-17T15:21:19Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/65675,yes,2.13.0,tf.data.Dataset.from_generator,Performance bug,Performance bug,Memory Leak,Memory Leak,Test Case Context,Oracle for Performance Bug Detection,,,,,2024-04-14T19:02:53Z,,
,https://github.com/tensorflow/tensorflow/issues/62927,yes,2.13.0,tf.keras.Model,Logical,TypeError,Unable to revive model from config,"TypeError: Unable to revive model from config. When overriding the `get_config()` method, make sure that the returned config contains all items used as arguments in the  constructor to <class '__main__.CustomModel'>, which is the default behavior. You can override this default behavior by defining a `from_config(cls, config)` class method to specify how to create an instance of CustomModel from its config. Received config={'name': 'custom_model', 'trainable': True} Error encountered during deserialization: __init__() missing 2 required positional arguments: 'inputs' and 'outputs'",Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2024-02-09T05:34:22Z,,
,https://github.com/tensorflow/tensorflow/issues/62778,yes,2.13.0,tf.shape,Logical,InvalidArgumentError,dimension 0 out of bounds,tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} slice index 1 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/ [[{{node numpy_function_1}}]] [Op:IteratorGetNext] name:,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2024-01-11T02:23:23Z,,
,https://github.com/tensorflow/tensorflow/issues/62509,yes,2.14.0,tf.tan,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-11-30T09:59:49Z,,
,https://github.com/tensorflow/tensorflow/issues/62509,yes,2.14.0,tf.math.reduce_prod,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-11-30T09:59:49Z,,
,https://github.com/tensorflow/tensorflow/issues/62504,yes,2.14.0,tf.squeeze,Vulnerability,Others,MemoryError: std::bad_alloc,"/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gen_array_ops.py in squeeze(input, axis, name)
  10614   if tld.is_eager:
  10615     try:
> 10616       _result = pywrap_tfe.TFE_Py_FastPathExecute(
  10617         _ctx, ""Squeeze"", name, input, ""squeeze_dims"", axis)
  10618       return _result

MemoryError: std::bad_alloc",API Input Context,Supporting Specific Data Types,,,,,2023-11-29T19:27:17Z,,
,https://github.com/tensorflow/tensorflow/issues/62441,yes,2.14.0,tf.nn.convolution,Performance bug,Performance bug,Memory Leak,Memory Leak,Test Case Context,Oracle for Performance Bug Detection,,,,,2023-11-20T15:51:19Z,,
,https://github.com/tensorflow/tensorflow/issues/62399,no,2.12.0,tf.math.log,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-11-14T23:45:40Z,,
,https://github.com/tensorflow/tensorflow/issues/61510,yes,2.13.0,tf.matmul,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Large Input Tensor,https://github.com/tensorflow/tensorflow/pull/61595,,,,2023-08-09T11:02:05Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61482,yes,2.13.0,tf.nn.max_pool2d,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-08-04T22:24:18Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61421,no,2.12.0,tf.debugging.experimental.enable_dump_debug_info,Logical,ValueError,Cannot assign a device for operation,"    output_tensor_device_ids = [writer.RegisterDeviceAndGetId(output.device)
ValueError: Cannot assign a device for operation IteratorGetNextAsOptional: Could not satisfy explicit device specification '' because the node {{colocation_node IteratorGetNextAsOptional}} was colocated with a group of nodes that required incompatible device '/job:worker/replica:0/task:0/device:TPU:0'. All available devices [/job:worker/replica:0/task:0/device:CPU:0, /job:worker/replica:0/task:0/device:TPU:0, /job:worker/replica:0/task:0/device:TPU:1, /job:worker/replica:0/task:0/device:TPU:2, /job:worker/replica:0/task:0/device:TPU:3, /job:worker/replica:0/task:0/device:TPU:4, /job:worker/replica:0/task:0/device:TPU:5, /job:worker/replica:0/task:0/device:TPU:6, /job:worker/replica:0/task:0/device:TPU:7, /job:worker/replica:0/task:0/device:TPU_SYSTEM:0, /job:worker/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:COMPOSITE:0]. ",Test Case Context,Modeling Multiple API Usage Pattern,,1,trigger: multiple api usage,,2023-07-28T06:27:06Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61369,no,2.13.0,tf.keras.layers.StringLookup,Logical,ValueError,Cannot set an empty vocabulary,"ValueError: Cannot set an empty vocabulary, you passed [].",API Input Context,Modeling Specific Inputs,Mohammad,,,,2023-07-24T17:57:32Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61364,no,2.12.0,tf.io.gfile.rename,Logical,FailedPreconditionError,Source is a directory or empty file,tensorflow.python.framework.errors_impl.FailedPreconditionError: Source is a directory or empty file,API Input Context,Modeling Specific Inputs,,,,,2023-07-24T14:39:54Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61344,yes,2.13.0,tf.data.Dataset.map,Performance bug,Performance bug,Memory Leak,Memory Leak,Test Case Context,Oracle for Performance Bug Detection,,,,,2023-07-20T20:36:51Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/61249,yes,2.13.0,tf.linalg.logdet,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Supporting Specific Data Types,,,,,2023-07-12T05:06:25Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61246,yes,2.13.0,tf.image.adjust_contrast,Logical,NotFoundError,Could not find device for node,NotFoundError: Could not find device for node: {{node AdjustContrastv2}} = AdjustContrastv2[T=DT_HALF],API Input Context,Supporting Specific Data Types,,,,,2023-07-11T16:05:56Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61162,yes,2.12.0,tf.io.read_file,Logical,ValueError,Shape must be rank 0 but is rank 1 for,   ValueError: Shape must be rank 0 but is rank 1 for '{{node ReadFile}} = ReadFile[](args_0)' with input shapes: [?].,API Input Context,Modeling Specific Inputs,,1,vectorizing the mapping function in the input triggers the bug,,2023-07-03T13:08:00Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61132,yes,2.14.0,tf.autodiff.ForwardAccumulator,Logical,TypeError,takes 2 positional arguments but 3 were given,TypeError: _SparseSparseMaximumGrad() takes 2 positional arguments but 3 were given,API Input Context,Supporting Specific Data Types,,,,,2023-06-30T19:23:24Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61117,yes,2.13.0,tf.math.reduce_prod,Logical,AssertionError,AssertionError,AssertionError: d2z_dydx = 0.0,API Input Context,Modeling Specific Inputs,,1,trigger: 0  elements in the input,,2023-06-28T16:17:39Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60929,yes,2.13.0,tf.matmul,Logical,RuntimeError,failed to prepare,"Keras mode output: [[16. 19.]] Lite mode output:  RuntimeError: tensorflow/lite/kernels/fully_connected.cc:360 NumElements(bias) != SizeOfDimension(filter, 0) (1 != 2)Node number 0  (FULLY_CONNECTED) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.",API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-06-20T02:32:43Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60925,yes,2.14.0,tf.concat,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-06-19T18:02:40Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60892,yes,2.13.0,tf.math.softplus,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Large Input Tensor,,1,trigger: large inputs after converting to lite model,,2023-06-16T05:05:57Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60861,yes,2.12.0,tf.data.Dataset.from_tensor_slices,Logical,TypeError,To be compatible with,"TypeError: To be compatible with tf.function, Python functions must return zero or more Tensors or ExtensionTypes or None values; in compilation of <function StructuredFunctionWrapper.__init__.<locals>.trace_py_function.<locals>.wrapped_fn at 0x7f88c9224c10>, found return value of type Operation, which is not a Tensor or ExtensionType.",Others,Others,,1,trigger: returning None doesn't work in the debug mode,,2023-06-14T14:21:08Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60765,yes,2.13.0,tf.raw_ops.AddN,Logical,AssertionError,Not equal to tolerance,"    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001",Test Case Context,Modeling Decorators for DL Execution Mode,,1,trigger is jti_compile mode with complex number,,2023-06-02T10:59:11Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60764,yes,2.12.0,tf.raw_ops.Acos,Logical,AssertionError,Not equal to tolerance,"    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001",Test Case Context,Modeling Decorators for DL Execution Mode,,1,trigger is jti_compile mode with complex number,,2023-06-02T10:50:29Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60759,yes,2.13.0,tf.raw_ops.Empty,Vulnerability,Check failed,Check failed,"2023-06-02 11:44:08.858309: F tensorflow/compiler/xla/shape_util.cc:288] Check failed: FillNewShape(element_type, dimensions, &shape) 
zsh: abort (core dumped)  python test.py",Test Case Context,Modeling Decorators for DL Execution Mode,,,,,2023-06-02T03:48:27Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60758,yes,2.13.0,tf.raw_ops.EmptyTensorList,Vulnerability,Check failed,Check failed,"2023-06-02 11:41:06.810728: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 246417692688323817 with 562326056, result: -1
zsh: abort (core dumped)  python test.py",API Input Context,Large Input Tensor,,,,,2023-06-02T03:41:51Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60757,yes,2.13.0,tf.raw_ops.Fill,Vulnerability,Check failed,Check failed,"2023-06-02 11:41:06.810728: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 246417692688323817 with 562326056, result: -1
zsh: abort (core dumped)  python test.py",API Input Context,Large Input Tensor,,,,,2023-06-02T03:22:05Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60756,yes,2.13.0,tf.raw_ops.GatherV2,Vulnerability,Check failed,Check failed,"2023-06-02 11:41:06.810728: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 246417692688323817 with 562326056, result: -1
zsh: abort (core dumped)  python test.py",API Input Context,Large Input Tensor,,,,,2023-06-02T03:14:31Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60714,yes,2.12.0,tf.split,Logical,ValueError,Check failed,"ValueError: Exception encountered when calling layer ""bn3"" (type BatchNormalization).
Shape must be rank 4 but is rank 5 for '{{node bn3/FusedBatchNormV3}} = FusedBatchNormV3[T=DT_FLOAT, U=DT_FLOAT, data_format=""NHWC"", epsilon=0.001, exponential_avg_factor=1, is_training=false](Placeholder, bn3/ReadVariableOp, bn3/ReadVariableOp_1, bn3/FusedBatchNormV3/ReadVariableOp, bn3/FusedBatchNormV3/ReadVariableOp_1)' with input shapes: [1,?,128,128,32], [32], [32], [32], [32].",API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-05-26T17:33:07Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60710,yes,2.12.0,tf.py_function,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-05-25T18:52:03Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60599,no,2.12.0,tf.data.Dataset,Performance bug,Performance bug,Memory Leak,Memory Leak,Test Case Context,Oracle for Performance Bug Detection,,,,,2023-05-15T14:54:49Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60583,yes,2.12.0,tf.data.Dataset.from_tensor_slices.rejection_resample,Logical,InvalidArgumentError,InvalidArgumentError,tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__DatasetToSingleElement_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Cannot batch tensors with different shapes in component 1. First element had shape [3] and element 1 had shape [2]. [Op:DatasetToSingleElement] name:,API Input Context,Modeling Specific Inputs,,1,trigger is: passing the ragged tensor through a differnt api called rejection_samples,,2023-05-12T10:16:39Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60549,no,2.12.0,tf.signal.inverse_stft,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,1,should be incorrect code pattern,,2023-05-09T20:14:39Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60547,yes,2.14.0,tf.linalg.matrix_rank,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Usage Context,Modeling Decorators for DL Execution Mode,,,,,2023-05-09T19:42:32Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60521,no,2.12.0,tf.nn.leaky_relu,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Usage Context,Supporting Specific Data Types,,,,,2023-05-06T09:03:07Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60472,yes,2.12.0,tf.where,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs," I suspect this because changing the input shape to (4, ) changes the output shape to (4, )",1,"it's inconsistent result, trigger is two differnt input argument",,2023-05-02T16:34:56Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60400,yes,2.12.0,tf.RaggedTensor.row_lengths,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,1,ragged tensor is the trigger,,2023-04-22T18:30:48Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60312,no,2.12.0,tf.nn.conv2d,Performance bug,Performance bug,Slow Execution,Slow Execution,Test Case Context,Oracle for Performance Bug Detection,,,,,2023-04-13T10:01:27Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60277,yes,2.12.0,tf.raw_ops.TridiagonalMatMul,Vulnerability,integer overflow,Aborted (core dumped),"2023-04-09 14:03:32.257496: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 6291163412844499803 with 7, result: -1
Aborted (core dumped)",API Input Context,Large Input Tensor,,1,integer overflow should be changed to checkfail,,2023-04-09T06:05:40Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60276,yes,2.13.0,tf.raw_ops.Gather,Vulnerability,integer overflow,Aborted (core dumped),"2023-04-09 14:03:32.257496: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 6291163412844499803 with 7, result: -1
Aborted (core dumped)",API Input Context,Large Input Tensor,,,,,2023-04-09T06:01:12Z,1,cu118
ACETest,https://github.com/tensorflow/tensorflow/issues/60275,yes,2.12.0,tf.raw_ops.MatrixLogarithm,Vulnerability,integer overflow,Aborted (core dumped),"2023-04-09 14:03:32.257496: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 6291163412844499803 with 7, result: -1
Aborted (core dumped)",API Input Context,Large Input Tensor,,1,integer overflow should be changed to checkfail,,2023-04-09T05:57:00Z,1,cu118
ACETest,https://github.com/tensorflow/tensorflow/issues/60273,yes,2.12.0,tf.raw_ops.UnicodeDecodeWithOffsets,Vulnerability,Check failed,Aborted (core dumped),"2023-04-09 13:47:12.779782: F tensorflow/core/framework/tensor.cc:770] Check failed: dtype() == expected_dtype (9 vs. 3) int32 expected, got int64
Aborted (core dumped)",API Input Context,Supporting Specific Data Types,,,,,2023-04-09T05:50:27Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/60239,yes,2.12.0,tf.data.Dataset.ragged_batch,Logical,ValueError,Tensor conversion requested dtype,"ValueError: Tensor conversion requested dtype variant for Tensor with dtype int32: <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>",API Input Context,Modeling Specific Inputs,,1,"trigger is when using debug mode, the normal one is ok",,2023-04-05T10:26:05Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60201,yes,2.12.0,tf.raw_ops.DepthwiseConv2dNativeBackpropInput,Vulnerability,InvalidArgumentError,Aborted (core dumped),"2023-04-01 16:37:55.854746: F tensorflow/core/kernels/mkl/mkl_conv_grad_input_ops.cc:537] Non-OK-status: tensor::MakeShape(input_tensor, &input_tf_shape) status: INVALID_ARGUMENT: Dimension -510 must be >= 0
Aborted (core dumped)",API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-04-01T08:40:42Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/60200,yes,2.12.0,tf.raw_ops.ThreadUnsafeUnigramCandidateSampler,Vulnerability,InvalidArgumentError,Aborted (core dumped),"2023-04-01 16:37:55.854746: F tensorflow/core/kernels/mkl/mkl_conv_grad_input_ops.cc:537] Non-OK-status: tensor::MakeShape(input_tensor, &input_tf_shape) status: INVALID_ARGUMENT: Dimension -510 must be >= 0
Aborted (core dumped)",API Input Context,Large Integer Argument,,,,,2023-04-01T08:36:16Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/60199,yes,2.12.0,tf.raw_ops.MatrixDeterminant,Vulnerability,integer overflow,Aborted (core dumped),"2023-04-01 16:27:45.620825: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 7678600331551628182 with 15, result: -1
Aborted (core dumped)",API Input Context,Large Input Tensor,,1,integer overflow should be changed to checkfail,,2023-04-01T08:30:49Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/60197,yes,2.12.0,tf.raw_ops.LearnedUnigramCandidateSampler,Vulnerability,Check failed,Aborted (core dumped),"2023-04-01 16:20:39.689581: F tensorflow/core/kernels/range_sampler.cc:183] Check failed: range < kint32max (3031324185113192368 vs. 2147483647)
Aborted (core dumped)",API Input Context,Large Integer Argument,,,,,2023-04-01T08:23:48Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/60196,yes,2.12.0,tf.raw_ops.StatelessRandomGammaV2,Vulnerability,Check failed,Aborted (core dumped),"2023-04-01 16:17:28.418600: F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count >= 0 (0 vs. -457139056)
Aborted (core dumped)",API Input Context,Empty Input Tensor,,,,,2023-04-01T08:21:17Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/60195,yes,2.12.0,tf.raw_ops.Conv3DBackpropFilterV2,Vulnerability,Check failed,Aborted (core dumped),"2023-04-01 15:05:15.267117: F ./tensorflow/core/util/tensor_format.h:427] Check failed: index >= 0 && index < num_total_dims Invalid index from the dimension: 1, 1, C
Aborted (core dumped)",API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-04-01T07:09:21Z,1,cu115
,https://github.com/tensorflow/tensorflow/issues/60165,no,2.12.0,tf.compat.v1.gfile.Rename,Logical,FailedPreconditionError,Source is a directory or empty file,"    _pywrap_file_io.RenameFile(
tensorflow.python.framework.errors_impl.FailedPreconditionError: Source is a directory or empty file",API Input Context,Modeling Specific Inputs,"Any resolution on this issue? The documentation states that tf.io.gfile.rename should work with directories. Again, this issue seems to be for S3 even with importing tensorflow_io. Local files seem to work. I haven't tried gcs or any other cloud provider. Other operations seem to work fine like checking if the folder exists in S3 with tf.io.gfile.exists",,,,2023-03-29T16:54:22Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60147,yes,2.12.0,tf.raw_ops.ResourceScatterUpdate,Vulnerability,Check failed,Aborted (core dumped),"2023-03-28 11:39:22.735062: F tensorflow/core/framework/tensor.cc:770] Check failed: dtype() == expected_dtype (1 vs. 2) double expected, got float
Aborted (core dumped)",API Input Context,Supporting Specific Data Types,,,,,2023-03-28T16:41:15Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60131,yes,2.12.0,tf.keras.applications.ResNet50,Performance bug,Performance bug,Memory Leak,Memory Leak,Test Case Context,Oracle for Performance Bug Detection,,,,,2023-03-27T15:36:35Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60059,yes,2.11.0,tf.raw_ops.QuantizeAndDequantizeV4,Logical,TypeError,takes 2 positional arguments but 4 were given,TypeError: _QuantizeAndDequantizeV4GradGrad() takes 2 positional arguments but 4 were given,Test Case Context,Modeling Multiple API Usage Pattern,,1,"2 arguments were passed, but expected 4, arguments are not matching",,2023-03-22T00:32:52Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/60041,yes,2.11.0,tf.math.zeta,Vulnerability,Inconsistent results,Inconsistent results,Inconsistent results,Others,Others,,,,,2023-03-20T05:15:05Z,1,N.A
ACETest,https://github.com/tensorflow/tensorflow/issues/60034,yes,2.11.0,tf.raw_ops.CholeskyGrad,Vulnerability,integer overflow,Aborted (core dumped),"2023-03-18 18:20:26.563113: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 1152921504606846976 with 8, result: -9223372036854775808
Aborted (core dumped)",API Input Context,Large Input Tensor,,,,,2023-03-18T10:22:30Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/59960,yes,2.11.0,tf.raw_ops.CholeskyGrad,Vulnerability,TypeError,takes 2 positional arguments but 4 were given,TypeError: _QuantizeAndDequantizeV4GradGrad() takes 2 positional arguments but 4 were given,Test Case Context,Modeling Multiple API Usage Pattern,,1,"2 arguments were passed, but expected 4, arguments are not matching",,2023-03-12T01:12:14Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/59927,yes,2.11.0,tf.compat.v1.nn.quantized_conv2d,Vulnerability,Check failed,Aborted (core dumped),"2023-03-08 10:44:30.202557: F tensorflow/core/kernels/quantized_conv_ops.cc:572] Check failed: out_cols > 0 (0 vs. 0)
Aborted (core dumped)",API Input Context,Empty Input Tensor,,,,,2023-03-08T02:46:25Z,1,cu115
,https://github.com/tensorflow/tensorflow/issues/59754,yes,2.11.0,tf.gather_nd,Logical,Others,Op: ResourceGatherNd,"Colocation members, user-requested devices, and framework assigned devices, if any:
  resource (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  ResourceGatherNd (ResourceGatherNd) /job:localhost/replica:0/task:0/device:GPU:0

Op: ResourceGatherNd
Node attrs: dtype=DT_COMPLEX64, Tindices=DT_INT64
Registered kernels:",API Input Context,Supporting Specific Data Types,,,,,2023-02-21T09:50:12Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/61646,yes,2.13.0,tf.config.experimental_connect_to_host,Vulnerability,AssertionError,Aborted,"E0819 19:02:10.839114974  187448 completion_queue.cc:244]    assertion failed: queue.num_items() == 0
Aborted",API Input Context,Modeling Specific Inputs,,,,,2023-01-22T16:31:20Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/61601,yes,2.13.0,tf.keras.layers.MaxPooling2D,Vulnerability,Check failed,Check failed,"{""pid"":7,""type"":""jupyter"",""level"":40,""msg"":""2023-08-17 14:34:29.104423: F tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:959] Check failed: cudnnSetPoolingNdDescriptor( handle_.get(), (pooling_descriptor.mode() == dnn::PoolingMode::kMaximum ? cudnn_max_pooling_mode : CUDNN_POOLING_AVERAGE_COUNT_EXCLUDE_PADDING), propagate_nans ? CUDNN_PROPAGATE_NAN : CUDNN_NOT_PROPAGATE_NAN, nd, shape.data(), padding.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)"",""time"":""2023-08-17T14:34:29.104Z"",""v"":0}",API Input Context,Large List Element,,,,,2023-01-22T15:48:36Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/59398,no,2.11.0,tf.train.CheckpointManager,Vulnerability,FailedPreconditionError,_NotOkStatusException,_NotOkStatusException: FailedPreconditionError: {{function_node __wrapped__SerializeIterator_device_/job:localhost/replica:0/task:0/device:CPU:0}} PyFunc is stateful. [Op:SerializeIterator],Test Case Context,Modeling Multiple API Usage Pattern,dependency issue,1,"the incorrect exception handling is an additional suggestion, not the trigger
The trigger is dependency problem",,2023-01-22T15:36:06Z,1,N.A
FuzzGPT,https://github.com/tensorflow/tensorflow/issues/61600,yes,2.13.0,tf.linalg.diag,Vulnerability,integer overflow,Encountered overflow,"Error:{{function_node __wrapped__MatrixDiagV3_device_/job:localhost/replica:0/task:0/device:GPU:0}} Encountered overflow when multiplying 12884901888 with 1610612736, result: -1
         [[{{node MatrixDiagV3}}]] [Op:MatrixDiagV3]",API Input Context,Large Integer Argument,,,,,2023-01-21T19:10:02Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/61603,yes,2.13.0,tf.compat.v1.keras.layers.MaxPool2D,Vulnerability,Check failed,Aborted,"2023-08-21 12:02:17.503892: F tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:983] Check failed: cudnnSetPoolingNdDescriptor( handle_.get(), (pooling_descriptor.mode() == dnn::PoolingMode::kMaximum ? cudnn_max_pooling_mode : CUDNN_POOLING_AVERAGE_COUNT_EXCLUDE_PADDING), propagate_nans ? CUDNN_PROPAGATE_NAN : CUDNN_NOT_PROPAGATE_NAN, nd, shape.data(), padding.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)
Aborted",API Input Context,Large List Element,,,,,2023-01-21T17:53:30Z,1,cu118
,https://github.com/tensorflow/tensorflow/issues/52064,yes,2.11.0,tf.keras.layers.Conv1D,Logical,RuntimeError,failed to prepare,RuntimeError: tensorflow/lite/kernels/reshape.cc:69 num_input_elements != num_output_elements (25000 != 0)Node number 2 (RESHAPE) failed to prepare.,API Input Context,Modeling Specific Inputs,,,,,2023-01-06T14:16:14Z,1,N.A
,https://github.com/tensorflow/tensorflow/issues/58790,yes,2.11.0,tf.math.cumsum,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,"My guess is that when doing cumsum on a ragged dimension, the summation is actually somehow carried out on the entirety of flat values, and then some subtractions based on row_splits turn the long cumsum list to the result at each dimension.",,,,2022-12-05T23:37:00Z,1,cu117
,https://github.com/tensorflow/tensorflow/issues/58628,yes,2.11.0,tf.distribute.experimental.rpc.Server,Performance bug,Performance bug,Memory Leak,Memory Leak,API Input Context,Oracle for Performance Bug Detection,,,,,2022-11-21T06:35:21Z,1,cu112
,https://github.com/tensorflow/tensorflow/issues/65675,yes,2.13.0,tf.data.Dataset.from_generator,Performance bug,Performance bug,Memory Leak,Memory Leak,API Input Context,Oracle for Performance Bug Detection,,,,,2024-04-14T19:02:53Z,,
,https://github.com/tensorflow/tensorflow/issues/62280,yes,2.14.0,tf.raw_ops.Acos,Logical,InvalidArgumentError,InvalidArgumentError,"    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''",API Input Context,Modeling Specific Inputs,,,,,2023-10-30T12:59:35Z,,
,https://github.com/tensorflow/tensorflow/issues/62263,yes,2.14.0,tf.raw_ops.SqrtGrad,Logical,InvalidArgumentError,InvalidArgumentError,"    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''",Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-10-28T02:08:02Z,,
,https://github.com/tensorflow/tensorflow/issues/62220,yes,2.14.0,tf.raw_ops.Asinh,Logical,InvalidArgumentError,InvalidArgumentError,"    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''",API Input Context,Modeling Specific Inputs,,,,,2023-10-25T07:04:01Z,,
,https://github.com/tensorflow/tensorflow/issues/62205,yes,2.13.0,tf.image.resize,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-10-24T08:24:07Z,,
,https://github.com/tensorflow/tensorflow/issues/62169,yes,2.14.0,tf.split_v,Vulnerability,Segmentation Fault,segmentation fault,[1]    13162 segmentation fault (core dumped)  ./benchmark_model --graph=../poc/split_v.tflite,Others,Others,,,,,2023-10-19T06:26:51Z,,
,https://github.com/tensorflow/tensorflow/issues/62168,yes,2.14.0,tf.reduce_prod,Vulnerability,Segmentation Fault,segmentation fault,[1]    13162 segmentation fault (core dumped)  ./benchmark_model --graph=../poc/split_v.tflite,Others,Others,,,,,2023-10-19T06:23:32Z,,
,https://github.com/tensorflow/tensorflow/issues/62167,yes,2.14.0,tf.pad,Vulnerability,Segmentation Fault,segmentation fault,[1]    13162 segmentation fault (core dumped)  ./benchmark_model --graph=../poc/split_v.tflite,Others,Others,,,,,2023-10-19T06:20:18Z,,
,https://github.com/tensorflow/tensorflow/issues/62166,yes,2.14.0,tf.onehot,Vulnerability,Segmentation Fault,segmentation fault,[1]    13162 segmentation fault (core dumped)  ./benchmark_model --graph=../poc/split_v.tflite,Others,Others,,,,,2023-10-19T06:16:31Z,,
,https://github.com/tensorflow/tensorflow/issues/62089,yes,2.13.0,tf.nn.depthwise_conv2d,Vulnerability,Others,_NotOkStatusException,"     55   except core._NotOkStatusException as e:

UnknownError: Graph execution error:",Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-10-11T12:42:52Z,,
,https://github.com/tensorflow/tensorflow/issues/61907,yes,2.13.0,tf.linalg.cholesky,Logical,NotFoundError,Could not find device for node,"NotFoundError: Could not find device for node: {{node Cholesky}} = Cholesky[T=DT_HALF]
All kernels registered for op Cholesky:",API Input Context,Supporting Specific Data Types,,,,,2023-09-19T05:37:10Z,,
,https://github.com/tensorflow/tensorflow/issues/61390,yes,2.11.0,tf.keras.layers.Dense,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Large Input Tensor,,,,,2023-07-25T19:38:25Z,,
,https://github.com/tensorflow/tensorflow/issues/61328,no,2.13.0,tf.keras.applications.efficientnet.EfficientNetB0,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-07-19T12:58:52Z,,
,https://github.com/tensorflow/tensorflow/issues/61313,yes,2.12.0,tf.data.Dataset.from_generator,Performance bug,Performance bug,Should be larger than,ResourceExhaustedError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Output buffer(size: 262144 bytes) too small. Should be larger than 19267611 bytes. [Op:IteratorGetNext],API Input Context,Large Input Tensor,,,,,2023-07-18T14:37:30Z,,
,https://github.com/tensorflow/tensorflow/issues/61162,yes,2.12.0,tf.data.Dataset.list_files,Logical,ValueError,Shape must be rank 0 but is rank,ValueError: Shape must be rank 0 but is rank 1 for '{{node ReadFile}} = ReadFile[](args_0)' with input shapes: [?].,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-07-03T13:08:00Z,,
,https://github.com/tensorflow/tensorflow/issues/61157,yes,2.13.0,tf.StridedSlice,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Generating Tensors with Incompatible Shapes,,,,,2023-07-03T07:56:16Z,,
FuzzGPT,https://github.com/tensorflow/tensorflow/issues/61060,yes,2.14.0,tf.linalg.LinearOperatorFullMatrix,Logical,ValueError,object of type,ValueError: TypeError: object of type 'LinearOperatorFullMatrix' has no len(),API Input Context,Modeling Specific Inputs,,,,,2023-06-22T13:59:15Z,,
,https://github.com/tensorflow/tensorflow/issues/60772,yes,2.12.0,tf.math.count_nonzero,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Large Input Tensor,,,,,2023-06-03T18:23:30Z,,
,https://github.com/tensorflow/tensorflow/issues/60654,yes,2.11.0,tf.math.abs,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-05-22T09:00:53Z,,
,https://github.com/tensorflow/tensorflow/issues/60628,no,2.11.0,tf.experimental.numpy.vander,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Zero Integer Argument,,,,,2023-05-18T15:11:22Z,,
,https://github.com/tensorflow/tensorflow/issues/60549,yes,2.14.0,tf.signal.stft,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-05-09T20:14:39Z,,
,https://github.com/tensorflow/tensorflow/issues/60485,yes,2.14.0,tf.math.cumsum,Logical,InvalidArgumentError,"OpKernel was found, but attributes didn't match","InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_cumsum_7[_XlaMustCompile=true,config_proto=3175580994766145631,executor_type=11160318154034397263] on XLA_CPU_JIT: Cumsum (No registered 'Cumsum' OpKernel for XLA_CPU_JIT devices compatible with node {{node Cumsum}}
         (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_INT8, Tidx=DT_INT32, exclusive=false, reverse=false){{node Cumsum}}",API Input Context,Supporting Specific Data Types,,,,,2023-05-03T16:51:04Z,,
,https://github.com/tensorflow/tensorflow/issues/60472,yes,2.14.0,tf.loop,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-05-02T16:34:56Z,,
,https://github.com/tensorflow/tensorflow/issues/60472,yes,2.14.0,tf.slice,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-05-02T16:34:56Z,,
,https://github.com/tensorflow/tensorflow/issues/60472,yes,2.14.0,tf.TensorArray,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-05-02T16:34:56Z,,
,https://github.com/tensorflow/tensorflow/issues/60262,no,2.13.0,tf.keras.callbacks.TensorBoard,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Modeling Specific Inputs,,,,,2023-04-07T03:33:16Z,,
,https://github.com/tensorflow/tensorflow/issues/60239,yes,2.12.0,tf.data.Dataset.ragged_batch,Logical,InvalidArgumentError,Traceback (most recent call last),"InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_1_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: Value [1 2] is not convertible to a tensor with dtype <dtype: 'variant'> and shape ().
Traceback (most recent call last):",Test Case Context,Modeling Multiple API Usage Pattern,,,,,2023-04-05T10:26:05Z,,
,https://github.com/tensorflow/tensorflow/issues/60149,yes,2.13.0,tf.data.Dataset.from_generator,Vulnerability,Check failed,Aborted (core dumped),"2023-03-28 12:06:28.440209: F tensorflow/tsl/platform/default/env.cc:74] Check failed: ret == 0 (11 vs. 0)Thread tf_data_private_threadpool creation via pthread_create() failed.
Aborted (core dumped)",API Input Context,Modeling Specific Inputs,,,,,2023-03-28T17:06:53Z,,
,https://github.com/tensorflow/tensorflow/issues/60121,yes,2.13.0,tf.raw_ops.AssignAddVariableOp,Vulnerability,Check failed,Aborted (core dumped),"2023-03-26 18:39:30.729731: F tensorflow/core/framework/tensor.cc:770] Check failed: dtype() == expected_dtype (3 vs. 1) float expected, got int32
Aborted (core dumped",API Input Context,Empty Input Tensor,,,,,2023-03-27T02:53:54Z,,
,https://github.com/tensorflow/tensorflow/issues/59702,yes,2.13.0,tf.cast,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Negative Input Tensor,,,,,2023-02-15T20:59:06Z,,
FuzzGPT,https://github.com/tensorflow/tensorflow/issues/60418,no,2.11.0,tf.saved_model.save,Logical,Others,because it is not built,"WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.meta_architectures.ssd_meta_arch.SSDMetaArch object at 0x7f45581d7340>, because it is not built.
WARNING:tensorflow:Skipping full serialization of Keras layer <object_detection.predictors.convolutional_keras_box_predictor.WeightSharedConvolutionalBoxPredictor object at 0x7f4558265760>, because it is not built.",API Input Context,Modeling Specific Inputs,,,,,2023-01-30T13:40:26Z,,
,https://github.com/tensorflow/tensorflow/issues/59215,yes,2.11.0,tf.debugging.enable_check_numerics,Logical,InvalidArgumentError,Graph execution error,InvalidArgumentError: Graph execution error:,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2023-01-10T14:12:55Z,,
,https://github.com/tensorflow/tensorflow/issues/59099,yes,2.11.0,tf.raw_ops.TensorListScatterV2,Logical,TypeError,EagerTensor of dtype variant,TypeError: Cannot convert 1 to EagerTensor of dtype variant,API Input Context,Modeling Specific Inputs,,,,,2023-01-04T20:44:47Z,,
FreeFuzz,https://github.com/tensorflow/tensorflow/issues/57935,no,2.11.0,tf.experimental.numpy.remainder,Vulnerability,InvalidArgumentError,Integer division by zero,InvalidArgumentError: {{function_node __wrapped__FloorDiv_device_/job:localhost/replica:0/task:0/device:CPU:0}} Integer division by zero [Op:FloorDiv],API Input Context,Zero Integer Argument,,,,,2022-10-01T21:59:46Z,,
,https://github.com/tensorflow/tensorflow/issues/57935,no,2.11.0,tf.experimental.numpy.floor_divide,Vulnerability,InvalidArgumentError,Integer division by zero,InvalidArgumentError: {{function_node __wrapped__FloorDiv_device_/job:localhost/replica:0/task:0/device:CPU:0}} Integer division by zero [Op:FloorDiv],API Input Context,Zero Integer Argument,,,,,2022-10-01T21:59:46Z,,
,https://github.com/tensorflow/tensorflow/issues/57838,yes,2.11.0,tf.keras.layers.Conv2D,Logical,InvalidArgumentError,Trying to access resource,InvalidArgumentError: Trying to access resource Resource-2-at-0x234d2850 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0 [Op:__inference___call___77],Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2022-09-26T03:32:38Z,,
,https://github.com/tensorflow/tensorflow/issues/57748,yes,2.11.0,tf.keras.layers.Conv2D,Logical,Others,CUDNN_STATUS_NOT_SUPPORTED,tensorflow.python.framework.errors_impl.UnknownError: CUDNN_STATUS_NOT_SUPPORTED,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2022-09-19T11:24:41Z,,
,https://github.com/tensorflow/tensorflow/issues/57744,yes,2.11.0,tf.math.log,Logical,Inconsistent results,Inconsistent results,Inconsistent results,Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2022-09-19T09:15:05Z,,
,https://github.com/tensorflow/tensorflow/issues/57664,yes,2.11.0,tf.keras.layers.Conv2D,Logical,ValueError,Exception encountered,"
    ValueError: Exception encountered when calling layer ""conv2d"" ""                 f""(type Conv2D).
    
    Negative dimension size caused by subtracting 2 from 1 for '{{node conv2d/Conv2D}} = Conv2D[T=DT_FLOAT, data_format=""NHWC"", dilations=[1, 1, 1, 1], explicit_paddings=[], padding=""VALID"", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](x, conv2d/Conv2D/ReadVariableOp)' with input shapes: [2,1,2,2], [2,2,2,1].
    
    Call arguments received by layer ""conv2d"" ""                 f""(type Conv2D):
      • inputs=tf.Tensor(shape=(2, 1, 2, 2), dtype=float32)",Test Case Context,Modeling Complex Tensor Operations and Layer Interactions,,,,,2022-09-11T09:08:08Z,,
,https://github.com/tensorflow/tensorflow/commit/28372efec3cc07a8e1db81f6b55b87ca4d87219b,no,2.13.0,tf.TensorArray.gather,Vulnerability,Segmentation Fault,Segmentation fault (core dumped),Segmentation fault (core dumped),API Input Context,Modeling Specific Inputs,,,,,2023,,
,https://github.com/tensorflow/tensorflow/commit/c5c0d33a365df5d8a81d920a9aeb0c390b67ee35,no,2.11.0,tf.image.convert_image_dtype,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Supporting Specific Data Types,,,,,2023,,
FuzzGPT,https://github.com/tensorflow/tensorflow/commit/bdf0934be81260b2e85aab9cba09bb77430f321c,yes,2.11.0,tf.custom_gradient,Logical,RuntimeError,is not supported when eager execution,Runtime Error:tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.,API Input Context,Modeling Specific Inputs,,,,,2022,,
,https://github.com/tensorflow/tensorflow/commit/bd4d5583ff9c8df26d47a23e508208844297310e,yes,2.11.0,tf.ragged.constant,Vulnerability,Check failed,Aborted (core dumped),Others,API Input Context,Large Integer Argument,,,,,2022,,
,https://github.com/tensorflow/tensorflow/commit/73c5ff37f15e385eb3541089b183a3a66907842d,yes,2.11.0,tf.debugging.assert_type,Logical,Inconsistent results,Inconsistent results,Inconsistent results,API Input Context,Supporting Specific Data Types,,,,,2020,,